### ISSUE TITLE
Remove Rea from dataprocessing to preprocessing

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#106]
At the moment the rea allocation of renewable power plants is a part of the data processing. 
Due to the random allocation algorithms the position of units is changing each time.

By placing the rea scripts as a preprocessing scripts the random allocation would be done only ones. Using an Update script of all different id's like sub_id the right relation of unit position and grid areas is given by having the same position.

**Comment by Ludee** [comment]
Unfortunately, this will not work because the REA needs the LA. MVGD and LVGD. We cannot reallocate without the finished eGoDP.
I think "preprcessing" should be defined more precisely. I understand it as setup (upload to oedb) and restructuring. The REA has assumptions and calculations that doesn't fit in "pre".

**Comment by wolfbunke** [comment]
Ok, thank you. If nobody has any other opinion I would leave rea in the dataprocessing.
