### ISSUE TITLE
Where are all them storages?

### ISSUE THREAD

**Issue by lukasol** [openego/data_processing#107]
I was wondering about existing storages (pumped hydro) in DE and the el. neighbours, but couldn't find any in the db...is that something we need to resolve (next week)?

**Comment by ulfmueller** [comment]
good point! We definitely should for v0.3. (and better also for the paper?!) The script is already [there](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/assignment_storage_bus.sql) ready for usage, I think. We had not integrated into the [dp](https://github.com/openego/data_processing/blob/feature/future-scenarios/dataprocessing/eGo_data_processing.py) because we thought that the timeseries/lopf script was still not ready for that. But I just went through the logic and I am pretty positive that we could just integrate that script and at least for the lopf it should work fine. Handling the storages as a flexible (and not variable) dispatch plant it does not need any p_max_pu series other than a fixed 1.

todo list proposal:
- [ ] debug the script locally, 
- [ ] e.g. I think max_hours is still pending to set (@Lukas maybe you can help here)
- [ ] check if there are more parameters missing
- [ ] check how/if the storages behave in the lopf
- [ ] integrate that script for the dp run 0.3
- [ ] may be execute that script for the model_draft concerning the publication

**Comment by lukasol** [comment]
Ok, looks like a good point for the power week. I could definitely help with the missing parameters, since there seem to be more missing than just max_hours. Let's how and with whom we can tackle this.

**Comment by lukasol** [comment]
Update for todo list proposal:
- [ ] debug the script locally, 
- [ ] check if storages are complete (including all electrical neighbours)
- [ ] e.g. I think max_hours is still pending to set (@Lukas maybe you can help here)
- [ ] check if there are more parameters missing
- [ ] check how/if the storages behave in the lopf
- [ ] integrate that script for the dp run 0.3
- [ ] may be execute that script for the model_draft concerning the publication

**Comment by lukasol** [comment]
Once there are exisiting and extendable storages in one table (ego_grid_pf_hv_storage), it can be quite hard to distinguish them. I would thus propose to add a new column to this table, which could just be named 'exisiting' and be of boolean type.

@ulfmueller @IlkaCu is that understood and would it be realistic (i.e. does it lead to vast changes at several places?)?

**Comment by lukasol** [comment]
Updated scripts to set existing storages to powerflow tables in https://github.com/openego/data_processing/commit/0fb133739d2791983fb1d15ef19153b115bfbc4f

With this script, all storages from BNetzA powerplant list are written to powerflow table. We need to clarify, how we deal with storages in neighbouring countries, that possibly come from renpassgis data. Will resolve that soon...maybe @s3pp could help.
