### ISSUE TITLE
Replace oemof.db dependencies if possible

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#13]
...and replace with ego.io tools.

**Comment by Ludee** [comment]
Is this issue closed? @gplssm
If not I move it to v0.3

**Comment by nesnoj** [comment]
Couldn't find any hard dependencies.

**Comment by nesnoj** [comment]
Oops, I got this wrong, sorry!
What @gplssm means is the use of oemof.db by data_proc (e.g. [here](https://github.com/openego/data_processing/blob/6a48404b69317552ff906ced2a54a441c4c26710/dataprocessing/tools/io.py#L10) or [here](https://github.com/openego/data_processing/blob/6a48404b69317552ff906ced2a54a441c4c26710/dataprocessing/python_scripts/peak_load_per_load_area.py#L19)). We definitely should import our [own db interface](https://github.com/openego/ego.io/blob/aa2913ed3ccec2813af36d1718c63a960149f672/egoio/tools/db.py) from ego.io instead of using oemof's.
I'll postpone this one to v0.3.

**Comment by nesnoj** [comment]
There're further discussions concerning this issue in https://github.com/openego/ego.io/issues/14

**Comment by gplssm** [comment]
We decided to do it differently and solve it by removing nasty dependencies in `oemof.db`  and discuss this in https://github.com/oemof/oemof.db/issues/32

**Comment by gplssm** [comment]
As written above: we don't solve the problem here, but hopefully in oemof.db itself.
