### ISSUE TITLE
Update database schema to v2

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#142]
Include feedback for the database schema structure.
Change names of the schemas and adapt in eGoDP.
It is based on ISO 19115 B.5.27 TopicCategoryCode.

Motivation: We are writing a short paper about the oedb and have one section about the schema structure. We want to include the updated version in the paper.

https://wiki.openmod-initiative.org/wiki/Database_schema#v0.2

political_boundary -> boundaries
weather -> climate
economic -> economy
environmental -> environment
social -> society

Do you know any other dependencies? Other eGo-tools? Please comment here.

**Comment by ulfmueller** [comment]
The ego.io would have to be updated.

**Comment by Ludee** [comment]
My plan is to collect all places here and execute it on Thursday 29th to be included in eGoDP v0.3.
Is that OK for you?

**Comment by lukasol** [comment]
plus several scripts in dp that use the schemes, e.g. the political boundary.

**Comment by ulfmueller** [comment]
I am usually not a big fan of renaming things because it often produce a lot of work without improving the results themselves, plus causing problems which were not expected.
If you (or s.o. else who wants to) adapt the entire dp to the new names and adapt the ego.io, it is ok for me. I guess since it is no change of structure but only a direct renaming the effort should be comparably small and bugs are rather unlikely.
I would suggest to do the change as smooth as possible. So I would suggest you create 

- [ ] a new branch in the dp where the names are adapted. 
- [ ] a new branch in the ego.io respectively
- [ ] test the branches locally (deluxe check, may be to much work)

Only after that I would 'execute' the renaming of the schema.

Sorry for the long answer. I am ok with it.

**Comment by Ludee** [comment]
That's a good idea and I planned to do it as a PR anyway.
I didn't had the ego.io in mind, thanks for that.

> I am usually not a big fan of renaming things because it often produce a lot of work without improving the results themselves, plus causing problems which were not expected.

I agree but I think the compatibility to ISO and INSPIRE is quite important.

**Comment by Ludee** [comment]
renaming of schemas completed! 
go for https://github.com/openego/oeplatform/issues/227 @MGlauer

**Comment by MGlauer** [comment]
Done

**Comment by Ludee** [comment]
Perfect. OEP is working and looks good, thank you!

**Comment by Ludee** [comment]
The renaming was merged and works.
