### ISSUE TITLE
Comment on temporary views

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#152]
I found many incorrect 'Comment on table' statements in the code which try to comment on views. 
See this [example](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_substation_hvmv.sql#L58-L64).
For the further debugging I will delete these 'comment on table' statements for all temporary views. From my point of view they are not essential as the views are deleted within the same script.

@Ludee: Where these queries added manually or automatically? Does any other code beside the DP snippets need to be adjusted to avoid this bug in the future?

**Comment by Ludee** [comment]
They were added semi-automatic in order to have a comment with the latest eGoDP version on every table in model_draft.
This way I wanted to identify all recent tables and find all old temp tables.

I think we agree that we don't need full metadata for temporary views/mviews/tables in model_draft.
What do you mean with "incorrect" comment? Do they give errors or just because they don't follow the metadata version? @IlkaCu

**Comment by IlkaCu** [comment]
They gave errors - but as far as I remember those comments where only applied for temporary mviews which where deleted in the same script. Removing those statements shouldn't be a problem.
