### ISSUE TITLE
column "metadata" of relation "ego_scenario_log" does not exist

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#169]
When executing the script 'ego_dp_powerflow_griddistrict_demand.py' I receive the following error: 

> ProgrammingError: (psycopg2.ProgrammingError) column "metadata" of relation "ego_scenario_log" does not exist
LINE 1: ...ript_name, entries, status, user_name, timestamp, metadata) ...
                                                             ^
 [SQL: 'INSERT INTO model_draft.ego_scenario_log (version, io, schema_name, table_name, script_name, entries, status, user_name, timestamp, metadata) VALUES (%(version)s, %(io)s, %(schema_name)s, %(table_name)s, %(script_name)s, %(entries)s, %(status)s, %(user_name)s, %(timestamp)s, %(metadata)s) RETURNING model_draft.ego_scenario_log.id'] [parameters: {'status': None, 'timestamp': datetime.datetime(2017, 9, 7, 14, 43, 40, 559717), 'io': 'input', 'schema_name': 'model_draft', 'metadata': None, 'table_name': 'ego_demand_loadarea', 'script_name': 'demand_per_mv_grid_district.py', 'version': 'v0.3.0', 'user_name': '', 'entries': 3607}]

In ego.io I checked the dev branch out. 
Furthermore I saw that in table ego_scenario_log the intended column is called 'meta_data'. But I do not find the place in the code where to fix it. @gplssm, @Ludee: Can you help?

**Comment by gplssm** [comment]
I would like to fix it, but I don't have access to the OEDB at the moment (a RLI issue).

I think this issue is related to the ORM specification of the table  'ego_scenario_log'. This table is defined in ego.io in file `model_draft.py`. 

```
class EgoScenarioLog(Base):
    __tablename__ = 'ego_scenario_log'
    __table_args__ = {'schema': 'model_draft'}

    id = Column(Integer, primary_key=True, server_default=text("nextval('model_draft.ego_scenario_log_id_seq'::regclass)"))
    version = Column(Text)
    io = Column(Text)
    schema_name = Column(Text)
    table_name = Column(Text)
    script_name = Column(Text)
    entries = Column(Integer)
    status = Column(Text)
    user_name = Column(Text)
    timestamp = Column(DateTime)
    meta_data = Column(Text)
```

You could change the last row of above ORM class to `meta_data = Column('meta_data', Text)`. This should point to the right column of the table.

**Comment by nesnoj** [comment]
@gplssm This will solve the problem for now, but in the next ego.io run you'll get the same error again so I'd not recommend to fix it this way.

There's are 2 issues related to the meta_data/metadata attribute: 
https://github.com/openego/ego.io/issues/21
https://github.com/openego/data_processing/issues/102

The bug was solved by renaming the column in all tables (see https://github.com/openego/data_processing/issues/102#issuecomment-307764645). So you may adjust your script to use `meta_data` as defined in [ego.io](https://github.com/openego/ego.io/blob/132791fa370ea7fc0bd5adee87b4190c7996750d/egoio/db_tables/model_draft.py#L3286).

HTH

**Comment by gplssm** [comment]
Hmm. I think I don't get it... The script calling class `EgoScenarioLog` [already uses `meta_data=...`](https://github.com/openego/data_processing/blob/50ba34c120025165ddb957c310c56152c3f2d838/dataprocessing/python_scripts/functions/ego_scenario_log.py#L76). As far as I understand, this should work with the class definition as shown in my comment above. 

Any hints appreciated!

**Comment by nesnoj** [comment]
> You could change the last row of above ORM class to `meta_data = Column('meta_data', Text)`. This should point to the right column of the table.

I do not get what's the difference? For me, it makes sense to rename/map a column if I wanna use a different name or if it's a reserved expression such as `metadata` (cf. no. 4 in [ego.io wiki](https://github.com/openego/ego.io/wiki/How-to-update-database-definitions)). But `meta_data` should work here - what's the matter redefining the name again using the same name? I do not get it..

Ok, back to start.

> SQL: 'INSERT INTO model_draft.ego_scenario_log (version, io, schema_name, table_name, script_name, entries, status, user_name, timestamp, **metadata**) VALUES (% .....

This output tells me, that a script (I guess `ego_scenario_log.py`) is using the wrong column name.
@IlkaCu: Is your stuff up-to-date?
1. Which DP version/branch r u using? 
2. Did u pull the latest version?

That's the only reason I can find at the moment...

**Comment by IlkaCu** [comment]
I'm using the DP branch 'release v0.3' and the dev branch in ego.io. 
Both branches are up to date. 
Up to now this is the only script which is affected and at the same time it is the only python script in the DP.

**Comment by IlkaCu** [comment]
I was wrong -It's seems that the installation of ego.io wasn't up-to-date on the server. I'll close this issue as soon as the script has finished.

**Comment by IlkaCu** [comment]
The script finished successfully. Thanks for your help.
