### ISSUE TITLE
decommissioning of conv. PP

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#178]
I have some questions concerning the conv. PP dataset:

I just discovered the `shutdown` column..
1. some PP in the SQ mview are shut down before 2015 (year of SQ scenario). In Dingo, I did not exclude these PP. Did you in the transmission part?
(actually, only 4 plants are affected in v. levels 4..7 but I have to cope with it nevertheless..)
2. There're 220 PP which are included in SQ mview but not in e.g. NEP 2035 mview. I assume they are decommissioned? (related issue in eDisGo: https://github.com/openego/eDisGo/issues/28)
Most of these datasets have no entry in the field `shutdown` - why?

I checked 2. using
```
SELECT sq.*
  FROM model_draft.ego_supply_conv_powerplant_sq_mview as sq
  WHERE NOT EXISTS (SELECT nep.bnetza_id
		      FROM model_draft.ego_supply_conv_powerplant_nep2035_mview as nep
		      WHERE sq.bnetza_id = nep.bnetza_id);
```

**Comment by wolfbunke** [comment]
Hey @nesnoj,
thanks for checking! I integrated the  `shutdown >=2015` in the sq_mview, [see here:](https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_conv_by_scenario.sql#L348)
 
To point two: we excluded all PP with the scenario capacity of zero in the mViews.
```
SELECT
count(*)
FROM
model_draft.ego_supply_conv_powerplant_2035
Where rated_power_b2035 <= 0;
```
which are 271. Also are some BNetzA ID's called several times due to different counting of blocks and power plants.

**Comment by nesnoj** [comment]
Thanks for fixing the 1st one!

But now I'm slightly confused..
I thought we only use 2 "base" tables `model_draft.ego_supply_conv_powerplant` and `model_draft.ego_supply_res_powerplant` and 3 MVIEWS for each of them (scenarios)?!
Why are u using the table `model_draft.ego_supply_conv_powerplant_2035`? I thought it is deprecated?

**Comment by wolfbunke** [comment]
The table` model_draft.ego_supply_conv_powerplant_2035 ` represents the original data from the NEP with all NEP scenarios as input and starting point for the further processing which ends in the `model_draft.ego_dp_supply_conv_powerplant ` as `scenario = "NEP 2035"`. In order to show you how many  power plants are set to zero/ decommission I was using this table which ist not filtered for my explanation. The naming with `2035` of this input table is maybe not the best and confusing.

**Comment by nesnoj** [comment]
Ok, thank you @wolfbunke !
Regarding 2): So I will assume these PP are decommissioned and *won't use* the column `shutdown` - right, @wolfbunke ?

**Comment by wolfbunke** [comment]
yes, that's the idea. But I really need to fined time to make the valuation next week.

**Comment by IlkaCu** [comment]
Is this still pending?

**Comment by nesnoj** [comment]
@wolfbunke is to close this issue as soon as he will have finished the validation..

**Comment by wolfbunke** [comment]
Yes

**Comment by IlkaCu** [comment]
@wolfbunke Did you finish the validation?

**Comment by wolfbunke** [comment]
not yet

**Comment by IlkaCu** [comment]
@wolfbunke: Are you planning to finish the validation mentioned above?

**Comment by IlkaCu** [comment]
@wolfbunke: Do you want me to shift this issue to another milestone than v0.3.1?

**Comment by wolfbunke** [comment]
Did it.

**Comment by wolfbunke** [comment]
The validation looks good and will be documented on ReadTheDocs http://data-processing.readthedocs.io/en/feature-readthedocs/scenario.html which is on work-in-progress.
