### ISSUE TITLE
Seperate wind into wind_onshore and wind_offshore

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#225]
For several reasons we should split the generator source wind = 13 in wind_onshore and wind_offshore. 

- assignment onshore and offshore time series
- see impact of offshore production in the system 
- ...

As fare as can see following tables need to be changed: 

Tables:
- model_draft.ego_grid_pf_hv_source
-  model_draft.ego_grid_pf_hv_result_generator
-  model_draft.ego_grid_pf_hv_result_generator_t
-  model_draft.ego_supply_pf_generator_single
- ...
Scripts:
- ego_dp_powerflow_assignment_generator.sql
- ego_dp_powerflow_timeseries_generator.sql
- ...
Please add missing tables and scripts.

What do you think?

**Comment by MarlonSchlemminger** [comment]
I agree that this should be implemented. It generally makes sense to be able to see the production split into on- and offshore and I had (and still have) some trouble during my work on #206 with only having "wind" as source.

**Comment by ulfmueller** [comment]
We used to say that the information about on- and offshore lies within the geometry of the plant. This applies to both of your mentioned motivations. The assignment of the time series depend on the location of a wind mill and respectively in which weather cell it is located. This is the same for the onshore power plant. So from a clear logical point of view the information mentioned is already there without the separation in two carrier types. Am I wrong?

Anyway if the adjustments are rather minor and without bigger effort doable I am ok with it. 

None of the tables (you mentioned) need to be changed in structure. So only the scripts would have to be changed. There has to be adjusted (at least) one more script: 
ego_dp_powerflow_hv_setup.sql
in this part the new source would have to be added: https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_hv_setup.sql#L1499-L1518

**Comment by MarlonSchlemminger** [comment]
> We used to say that the information about on- and offshore lies within the geometry of the plant. This applies to both of your mentioned motivations. The assignment of the time series depend on the location of a wind mill and respectively in which weather cell it is located.

Both the geometry and the generation subtype is neither available in ego_supply_pf_generator_single nor in ego_grid_pf_hv_generator. This makes it really hard to find out if a generator is on- or offshore, because you have to go really far back into the process to get these information. I think issue #222 made this clear as well, where you need to write complicated join statements for a rather simple information. I am generally a fan of doing things explicitly instead of implicitly and I don't see a negative impact of having on- and offshore seperated in all tables.

Specifically for the process in #206, we encountered problems where one weather cell on coastal regions would have both on- and offshore generators where the assignment simply by weather cell does not work.

**Comment by ulfmueller** [comment]
I am ok with it and I also see the advantage. I just hope the general logic is kept and no special (buggy) work-around is created. Just by the way, explicitly keeping information can also mean to create carriers such as southern, northern, eastern, western, big, small (...) 'solar' which would be not desirable... so I guess it is not a 'black or white' issue.

Do you consider this change then also for the neighboring countries? To be consistent the should be divided in off and onshore as well...

Is it all clear now or is there more need for discussion/clarification? 

So in the ego_dp_powerflow_assignment_generator.sql the wind power plants will get with respect to the power plant location (or with respect to the generation subtype?!)an on or offshore source id which will be set in the generator_single table and then you can simply use that information for your assignment of time series?!

**Comment by MarlonSchlemminger** [comment]
> I am ok with it and I also see the advantage. I just hope the general logic is kept and no special (buggy) work-around is created. 
My goal is to increase the general logic and don't implement any work-arounds. 

> Just by the way, explicitly keeping information can also mean to create carriers such as southern, northern, eastern, western, big, small (...) 'solar' which would be not desirable... so I guess it is not a 'black or white' issue.
I think the differentiation between on- and offshore wind is reasonable without the need to differentiate between things like roof- and ground-mounted solar. Most studies seperate on- and offshore wind, whereas solar is just solar, so I think we are fine here.

> Do you consider this change then also for the neighboring countries? To be consistent the should be divided in off and onshore as well...
This would definitely be my plan, yes.

> Is it all clear now or is there more need for discussion/clarification?

So in the ego_dp_powerflow_assignment_generator.sql the wind power plants will get with respect to the power plant location (or with respect to the generation subtype?!)an on or offshore source id which will be set in the generator_single table and then you can simply use that information for your assignment of time series?!
I didn't put any work into the detailed implementation, it is more a general idea so far, so I can't say yet how much clarification I will need. The goal would be to make this based on the generation subtype. This looks simple because it is an information we already have and we could get new bugs if we make it based on the location.

I would first finish my work on issue 206 (hopefully until the weekend) and could then put more work into this issue.

**Comment by ulfmueller** [comment]
@IlkaCu but then due to the time plan this is probably not part of v0.3.1, right?
Is it possible that the so far changes you made with the direct integration can be included but without this offshore onshore differentiation? or do we get a bigger 'error'/problem then?

**Comment by MarlonSchlemminger** [comment]
Yes I think we can include this, this is what I am currently testing.

**Comment by IlkaCu** [comment]
> @IlkaCu but then due to the time plan this is probably not part of v0.3.1, right?
Would be nice to include these changes in the v0.3.1 version already. I will think about the adjustments we/I need to implement it in the DP and let you know tomorrow whether I think this is realistic in v0.3.1 or not.

**Comment by IlkaCu** [comment]
I would like to include these changes in the v0.3.1 release. 
@MarlonSchlemminger: Did you already create a new branch for these changes? 
There are some other scripts beside ego_dp_powerflow_assignment_generator.sql , which I will adjust when you included your changes. This concerns the scripts ego_dp_powerflow_hv_setup.sql, ego_dp_powerflow_lopf_data.sql and of course ego_dp_powerflow_assignment_generator.sql.

**Comment by MarlonSchlemminger** [comment]
I created a local branch, but didn't do anything yet in it and didn't push it. I am done with my work on 206 and will start working on this now.

**Comment by MarlonSchlemminger** [comment]
Another thing I realized during the last days which is related to this issue is that full load hours for both wind on- and offshore are too high. We have average full load hours of 2600 for onshore and 4300 for offshore, some offshore parks even have 6000 full load hours. After talking to @s3pp , we decided that I will try to find correction factors to bring down the production to a realistic level. This should probably be included in the release as well.

**Comment by MarlonSchlemminger** [comment]
Quick update: I implemented my changes on Friday and started the assignment_generator-Skript and it failed yesterday after 48 hours with a primary key constraint violated. I don't know yet what mistake I made and the long runtime makes it difficult to find out. Given that the Fachtagung starts on Thursday means that I don't think I will be done with this this week.
I've pushed my local branch regardless: https://github.com/openego/data_processing/tree/features/seperate-wind-on-offshore

**Comment by s3pp** [comment]
Just reading into this @MarlonSchlemminger, because of #220 I rewrote parts of timeseries_generator in python. If this isn't helpful atm, than feel free to ignore it https://github.com/openego/data_processing/commit/32026ec5014e2f34f2b4191904cf787be5574751.

**Comment by IlkaCu** [comment]
Can this issue be closed to to the pull request #233?
