### ISSUE TITLE
Storages in AT and LU missing

### ISSUE THREAD

**Issue by lukasoldi** [openego/data_processing#274]
Storage assignment in neighbouring countries has been an issue in #129 already. The translation from renpass gis data to powerflow happens here:

https://github.com/openego/data_processing/dev/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L345

For all neighbouring countries, storages are taken from the table calc_renpass_gis.renpass_gis_storage where AT and LU have capacities. Check via:

`select * from calc_renpass_gis.renpass_gis_storage where scenario_id = '41';`

But somehow for these two countries, no capacity makes it to the final powerflow data. Check via:

`select * from grid.ego_pf_hv_storage where version = 'v0.4.0' and scn_name = 'NEP 2035' and storage_id > 200000;`
(it's the same for all recent versions)

Do you have any clues here?

**Second question**, primarly to @wolfbunke: why is there no pumped storage capacity for Sweden? The ENTSO-E data sees something there and if I am not mistaken there are several ones in Sweden.

**Comment by wolfbunke** [comment]
I am working / check here on your question https://gist.github.com/wolfbunke/c662a15fd016f367ccce0adf8ac9cb70 . I hope that I have  everything solved tomorrow.

**Comment by wolfbunke** [comment]
> Second question, primarly to @wolfbunke: why is there no pumped storage capacity for Sweden? The ENTSO-E data sees something there and if I am not mistaken there are several ones in Sweden.

We had a debate on storages of Sweden because of several different definition (reservoir hydropower plant, run of river or pumped Hydropower)  we decided to define it as hydro. Which was later changed  run_of_river. I think we should definitely change it for SE, if you have better / detailed data. Can you send the ENTSO-E data link please.

**Comment by IlkaCu** [comment]
FYI: I stopped the DP run v0.4.1 right before the assignment_storage script. Once you are done with your adjustments please let me know. Then I'll proceed the run.

**Comment by ulfmueller** [comment]
@IlkaCu I guess this  #275 implies a possible change to possibly wait for (if there is a fast and good decision)...

**Comment by wolfbunke** [comment]
The bug is fixed in #283. I checked the number of storages and country per scenario

|scn_name | no counties| no storages|
|--------------|---------------|----------------|
|  SQ          | 5                | 5                 |
| NEP 2035| 6                | 6                 |
|ego100     | 9                | 40     *        |

\* introduced more technologies

**Comment by wolfbunke** [comment]
I updated the docu for SQ and NEP in https://github.com/znes/FlEnS/tree/features/ego-timeseries/open_eGo/

**Comment by wolfbunke** [comment]
I guess we can close this issue, right?

**Comment by lukasoldi** [comment]
Yes, this works from version v0.4.1.
