### ISSUE TITLE
complete reference list

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#319]
Hey all,

I'm wondering whether we have an exhaustive reference list for the data used in DP? I'm aware of the BPMN and the table metadata, but it would require some work to join all the information..

**Comment by nesnoj** [comment]
Comments, anyone?

**Comment by ulfmueller** [comment]
I like the idea. I guess this list would be part of rtd, right? 
I just do not know when we find time for this. Do you want this very soon or can we start listing successively and find a deadline day which I would rather see in October?

**Comment by nesnoj** [comment]
:laughing: 

Ok, I found someone who can start working on this right now.
More sources to be considered except metadata? I'm afraid that the metadata of some tables are incomplete..

**Comment by nesnoj** [comment]
One more thing:
Do you prefer a ReST table or reference list? Example [here](https://dingo.readthedocs.io/en/dev/about.html)

**Comment by ulfmueller** [comment]
I'd say if you link it to tables/scripts a table otherwise a reference list...

**Comment by nesnoj** [comment]
Ok, @01lillyschoen09 will create a ReST reference list in the following format:
`[SourceYear] Source: Name, Year, License, Link`

If you have comments on this, please reply fast..

**Comment by nesnoj** [comment]
@wolfbunke Could you please enable automatic creation (hook) of branch feature/readthedocs for RTD as it does not seem to be created automatically.. and I cannot build a new one on RTD.

**Comment by wolfbunke** [comment]
It doesn't create all Documentation automatically at the moment, therefore we (@IlkaCu ) turned it off. The reason is, that  you need to run the build_script_doc.py script in https://github.com/openego/data_processing/blob/feature/readthedocs/documentation/build_script_doc.py in order to create the preprocessing and dataprocessing docs of the SQL header. Do you have a readthedocs account? Write me an email and I can add you to the DP readthedocs.

I just started a update/ new creation of the branch.

**Comment by nesnoj** [comment]
Discontinued
