### ISSUE TITLE
Missing tables: model_draft.ego_supply_res_powerplant_sq_mview and model_draft.ego_supply_conv_powerplant_sq_mview

### ISSUE THREAD

**Issue by OriolRaventos** [openego/data_processing#326]
The file ego_dp_structure_input_verification.sql used in dataprocessing.py uses the following two tables that do not exist in the data base:

https://github.com/openego/data_processing/blob/137f4c1815d8ce7f1987cd0ff01c53c4661e3118/dataprocessing/sql_snippets/ego_dp_structure_input_verification.sql#L134-L135

Should the tables **model_draft.ego_supply_res_powerplant** and **model_draft.ego_supply_conv_powerplant** be used instead?

Note: This seems to be related to the ISSUE https://github.com/openego/data_processing/issues/109

**Comment by nesnoj** [comment]
> Should the tables model_draft.ego_supply_res_powerplant and model_draft.ego_supply_conv_powerplant be used instead?

No.

These 2 entities are not tables but [materialized views](https://www.postgresql.org/docs/10/rules-materializedviews.html). When querying (as in your example above) there's no difference between a table and a view/mview, that's why the suffix "mview" was used in DP.
I just looked up and both do exist although not visible in the OEP dataview.
