### ISSUE TITLE
mvgd multipolygon bug

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#39]
MVGD are mulitpolygons and some have parts without TP.
See internal presentation.

**Comment by nesnoj** [comment]
This is definitely a problem for dingo. About 6% of MVGDs are affected according to @Ludee.
We prefer to leave the current GD script as it is and treat the buggy MVGDs afterwards.
This issue can be solved in different ways, e.g.:

1. Allocate (union) affected MVGD x to the MVGD which is located next to the centroid of x (preferred method since it is relatively simple to implement)
2. Allocate (union) affected MVGD x to the MVGD which shares the longest border with x (probably better results but too complex to implement)

@IlkaCu @ulfmueller @lukasol: Do you agree with solution 1?

**Comment by Ludee** [comment]
There is now a table **model_draft.ego_grid_mv_griddistrict_new** with less multipolygons.
The number is reduced from 268 (7,4%) to only 116 (3,2%) of which most are "real" islands.
Only two fragments are no islands but too crazy to be eliminated.

![mvgd_multibug_1](https://cloud.githubusercontent.com/assets/14353512/24203807/03fbd724-0f17-11e7-90de-23feb9786ebf.png)
![mvgd_multibug_2](https://cloud.githubusercontent.com/assets/14353512/24203810/05cc82ce-0f17-11e7-9f60-e70e750f6c4e.png)

If wanted it can be implemented in the v0.2 run!? @nesnoj @gplssm @ulfmueller

**Comment by nesnoj** [comment]
yea!
