### ISSUE TITLE
merge eGoDP v0.2 (refactor branch) in master branch

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#42]
I cannot find info and decisions about the planning of the merge?
Who is responsible?
Please add info and planed timetable.

**Comment by lukasol** [comment]
@ulfmueller agreed to coordinate this with our help. As far as I know there is no schedule yet, but ZNES should decide which issues are still to be resolved in version 0.2 and which migrate to version 0.3.

**Comment by Ludee** [comment]
Last week I went through all issues and closed v0.1. Then only left the **must solve** or **perhaps already solved** in v0.2. All other **nice to have** went to v0.3.

An announced schedule and a date for the merge would be good to don't interrupt other work in progress.

**Comment by ulfmueller** [comment]
I totally agree. I have a meeting on this tomorrow afternoon together with Ilka. We will make a schedule and annouce it. If we have questions or are not sure in some points we will ask...

**Comment by nesnoj** [comment]
Please consider necessary changes to setup.py (if any)

**Comment by IlkaCu** [comment]
As mentioned in the redmine-News we will rename the DP-branches tomorrow. The current  branch 'oedb-restructuring_v0.2' will be our new master branch, which then will be the basis for the new dev-branch. The current master branch will from that point on function as an archive. 
This process is quite decoupled from the pending tasks for the release eGoDP v0.2.

**Comment by lukasol** [comment]
Please try closing #34 before the merge.

**Comment by s3pp** [comment]
We renamed the current master to archive_v0.1. Additionally a new master branch was created checking out refactor/oedb-restructuring_v0.2. As a consequence master branches locally and remotely are not the same anymore. If you try to pull the master branch a merge would be the result. The easiest way to reconfigure the master branch locally is to rename or delete it and to pull the new master branch once again from the remote (or just clone the repository again). A dev branch was also created reflecting the latest state of refactor/oedb-restructuring_v0.2. We intent to keep the refactor branch for a short time just to make sure everything is fine and then delete it. The dev branch is the place for further development as of now. If you accidently work on the refactor branch in the next days, because its still there as of now, on noticing those changes can easily merged back into the dev branch.

**Comment by nesnoj** [comment]
I assume the rest will be done in the course of v0.2 release #35.

**Comment by IlkaCu** [comment]
That's right!
