### ISSUE TITLE
Integration of LV in eGoDP

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#47]
The methods for the LV (substation, grid districts) are not properly integrated into the eGoDP.
I will list my major concerns and ideas in this issue:

- [x] Table name of the LV substations is _ego_grid_mvlv_onts_. ONTS (Ortsnetztrafos) is a German abbreviation and doesn't fulfil the naming convention (also plural s) -> **ego_grid_mvlv_substation** see [Wikipedia](https://en.wikipedia.org/wiki/Electrical_Substation#Distribution_substation)
- [x] Methods are all in only two scripts (_process_eGo_onts.sql_ and _process_eGo_lv_grid_districts.sql_). I made some suggestions to split them up to be more modular and easy execution (see appendix)
- [x] Documentation of inputs, outputs and licenses in bpmn

appendix:
> Das Skript process_eGo_lv_grid_districts.sql scheint ja noch nicht richtig zu laufen. Also hier meine Ideen dazu. Zunächst ist es viel zu lang. Zerlegen in
·         Voronoi
·         Cut
·         Sectors
·         Peak load
Dann können einzelne Teile leichter verändert und ausgeführt werden.

**Comment by Ludee** [comment]
any feedback @jong42 ?

**Comment by jong42** [comment]
I can split up the script and add BPMN documentation when I finished my thesis but right now I have no time available for it. After 6th March I can deal with the script.

**Comment by nesnoj** [comment]
I've done most of 3. (BPMN stuff) in 1dbde653eed9d991e83b6bfbfc9a3e9e638e5228

**Comment by nesnoj** [comment]
@jong42 I've got 3 more issues on this (but I only need your support on 3.)

1. I've seen your approach to calc demand in [process_eGo_lv_grid_districts.sql](https://github.com/openego/data_processing/blob/0f0916c98025547338b6ff2fdebc3109910daf28/dataprocessing/sql_snippets/process_eGo_lv_grid_districts.sql). Don't worry about it since the most reasonable approach is to use the method from load area demand calculation and map it on the LV grid districts. We'll take care of this (I commented out in db4bf84d59841fa360f1f436b81d3bcfa235877b)
2. To have a relation between LV grid districts and MVLV substations I added an additional column which is now set (9ff5c590da6c3ea812598bc0d40b8e418454a12d).
3. There're more than 50k LVGD without a MV/LV substation. In your script there's a [part](https://github.com/openego/data_processing/blob/0f0916c98025547338b6ff2fdebc3109910daf28/dataprocessing/sql_snippets/process_eGo_lv_grid_districts.sql#L246-L267) to handle them but obviously I doesn't work?! They aren't merged into adjacent LVGD with substation.. any hints on this?

**Comment by jong42** [comment]
I will look into this but I'd like to postpone it after my thesis is finished on march 6th. Let me know if you absolutely need it fixed before that date.

**Comment by Ludee** [comment]
There is an orphaned script named **process_eGo_lv_streets.sql**.
It still calls some **calc** tables that are out of date.
See #38

**Comment by nesnoj** [comment]
There's some unused LV stuff I'll clean up until the 10th.

**Comment by Ludee** [comment]
I started the restructuring and adapting of tested methods from the MV part to the LV part.

**Comment by Ludee** [comment]
Can you please close this issue when you are done with the BPMN @gplssm
