### ISSUE TITLE
Duplicate tables in supply schema

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#51]
What's the difference between the following tables? 
_supply.ego_renewable_power_plants_germany_
_supply.ego_res_powerplant_

Is it a duplicate?

**Comment by wolfbunke** [comment]
I took a look into the table due to the first oep presentation and the changes of our DB structure we have now two similar tables. I add @Ludee in order to know which table open_Fred is using. 

* supply.ego_renewable_power_plants_germany is an older version, which was done as show case for the oep presenatation / workshop in Berlin but is in use of open_Fred? Or?
* supply.ego_res_powerplant is a newer version

in both cases the changes are small e.g. delete of obviously wrong data, meta data, comments in the data table,.... 

For the next step I would write a comment under notes and for the long term we should delete one table and/or update the other table. 

What do you think? @Ludee @IlkaCu

**Comment by Ludee** [comment]
I would prefer a close link to OPSD. I thought it was a simple copy. 

> in both cases the changes are small e.g. delete of obviously wrong data, meta data, comments in the data table,....
If data is processed it doesn't belong in the **supply** scheme. 
If you adjust the OPSD-Tables for open_eGo, it belongs in model_draft.

> .. and for the long term we should delete one table and/or update the other table.
Why long term? Just drop it if it doesn't follow the rules and get a citable and transparent data set immediately.

**Comment by IlkaCu** [comment]
In the moment we change the 'original' table twice. Once in the pre-processing where we delete or correct corrupt entries and adjust the voltage_level according to our allocation table (see #48) and the second time in the dataprocessing itself, where we assign subst_id and otg_id to every power plant. 
I would suggest to have the original OPSD-table in the supply schema and a modified table including all changes in the model_draft. From my point of view this would be an adjustment associated to v0.3. Any other suggestions?

**Comment by Ludee** [comment]
I agree with your suggestion, this is what I intended. 
But I disagree with a delay to an unscheduled v0.3. This was/is the main focus of v0.2 to move all input data in the "new schema structure", remove all old dependencies ("calc") and put all processed data in model_draft.

**Comment by IlkaCu** [comment]
Right, this is closely related to issue #43 which is also part of v0.2

**Comment by IlkaCu** [comment]
I copied the processed power plant lists into the model_draft schema. 
supply.ego_res_powerplant --> model_draft.ego_supply_res_powerplant
supply.ego_conv_powerplant --> model_draft.ego_supply_conv_powerplant

If no one disagrees, I would delete the old tables soon. 
@nesnoj: Please adjust your depending scripts according to this changes.

**Comment by nesnoj** [comment]
Go for it.
@Ludee: R u gonna adjust your alloc scripts?

**Comment by Ludee** [comment]
Please delete or move the outdated table:
- [ ] supply.ego_renewable_power_plants_germany

Also remove the columns subst_id, otg_id and un_id from supply.ego_res_powerplant.
I think they don't belong in the "original" table.

**Comment by Ludee** [comment]
Status?
