### ISSUE TITLE
centralize version numbering

### ISSUE THREAD

**Issue by ulfmueller** [openego/data_processing#71]
When executing a new run of data processing the version number has to be changed in all scripts several times.
I would suggest to develop a more object-oriented, less decentralized, leaner approach. 
Why not enter the version number (logging function) only in the executing file https://github.com/openego/data_processing/blob/dev/dataprocessing/eGo_data_processing.py ?

The only thing which would be missing would be the intra-file logging. Which I think would be ok.

**Comment by Ludee** [comment]
The main problem is that is difficult (I could not find a solution) to pass a variable (version number) from one file to a SQL file.
Because I work with notepadd++, I also track a "session" (eGo_dataprocessing_session.txt) with all files. Then it is only one search and replace in all files. It is not perfect but at least we have a working versioning system now.
Please feel free to improve this concept!

One possible option is to use the scenario list (model_draft.ego_scenario) instead of the hard-coded version number.

**Comment by ulfmueller** [comment]
on linux I did it now with this:
`find /path/to/data -type f -exec sed -i 's/v0.2.9/v0.2.10/g' {} \;`

**Comment by Ludee** [comment]
New version of the **scenario_log** for multiple projects still has a hard-coded version number in it.
It is a little work to update it in all scripts but new versions are not released very often.
