### ISSUE TITLE
Shortest path assignment

### ISSUE THREAD

**Issue by s3pp** [openego/data_processing#74]
As can be seen in the image below there are hv - buses (circles) that seem not to be allocated to the next substation (squares). All hv - buses are coloured based on the nearest substation. Beige-coloured buses are allocated to the southern substation, blue - coloured buses to the northern substation. It seems that the nearest substation for some hv - buses coloured in beige should be the northern substation. It think it's not per se an issue with the shortest path algorithm, questionable buses (at least those two in the north) have indeed no connection to the underlying line, although it seems that there could potentially be a connection. Long story short is this something I should worry about? Do you know what I mean?

![20170410_gridhvbusassignment](https://cloud.githubusercontent.com/assets/10025949/24860376/977c23dc-1df4-11e7-9acd-ef66638a46b7.png)
-------------------------------------------------------------
![20170410_gridhvbusassignment2](https://cloud.githubusercontent.com/assets/10025949/24860430/d6f58170-1df4-11e7-838e-cb19b51a011f.png)

**Comment by lukasol** [comment]
You're right, that looks odd. 
Can you provide some more info, e.g. IDs of the buses and the dataset you used?

The connection of buses to lines they are "on" with the same voltage is normally ensured with a specific function, but I can check this particular case. Are there more occurrences like this?

**Comment by s3pp** [comment]
Of course, sry, the bus_id of the most relevant bus is 10227. The underlying line connects 9899, 23943. The dataset was exported from the db on the 29.03., maybe something was going on during that time, haven't thought about that error source until now.

**Comment by s3pp** [comment]
Regarding, whether or not there are more occurrences, I will have a look at it again.

**Comment by lukasol** [comment]
I assume you do not distinguish the type of the HV bus, right?

In our grid model, there are substations (identified as such if there is substation_id) and joints. The latter are basically just nodes connecting lines, but there are no generators or loads connect to them. Thus, I would think that the connection of these joints to the closest EHV-substation is not really relevant.

Let's also ask @ulfmueller for his opinion.

**Comment by s3pp** [comment]
You're right, the distinction between substations and joints is not made. However, on a side note, I preselected those HV - buses, that are part of the grid, connected by lines. Only for those buses the algorithm is executed. I agree that it is not an issue if only joints are concerned. Looking through the data I did not find something similar.

**Comment by ulfmueller** [comment]
Certainly joints are not relevant for the aggregation and can be neglected (might improve calculation time substantially?!). But that does not tackle this problem, right?

Anyhow, the shortest path algorithm seems to work fine in this case (here maybe the shortest direct distance would be cynically better) and the underlying logic makes sense. This is an issue about data quality  (and/or abstraction algorithms of osmTGmod). I would not bother about it too much. It is a nice example concerning further validation of the data. It might be even possible that it is even just reality like that. It would be interesting to have a resulting regions-graphic of the ehv-cluster due to the shortest-path-method and lay it over the pure voronoi region graphic. That could be a nice validation also for student works!

**Comment by s3pp** [comment]
Thanks for your feedback @ulfmueller, @lukasol! I added the proposed validation method to our nice-to-have topics. For the moment I leave it that way then.
