### ISSUE TITLE
Wrong data in model_draft.ego_supply_res_powerplant

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#81]
The current data in table model_draft.ego_supply_res_powerplant contain some bugs in voltage_level and generation_subtype. 
I tested the [preprocessing code](https://github.com/openego/data_processing/blob/release/v0.2.6/dataprocessing/sql_snippets/ego_dp_preprocessing_res_powerplant.sql) locally and this script does not create the faulty entries. 
An example is the re-generator with id=1559782 which is an offshore wind power plant connected to the EHV level, but currently it is assigned to voltage_level 5 and is declared as an onshore wind turbine. 

@nesnoj, @Ludee, @wolfbunke: Do you know of any other scripts changing the voltage_level or generation_subtypes in table model_draft.ego_supply_res_powerplant?

**Comment by nesnoj** [comment]
Not sure about this. Currently there's a bug in the REA allocation but as far as I know no changes are made regarding these 2 columns - right, @Ludee?
Concerning your question via mail: I think `model_draft.ego_supply_rea` is obsolete, we use the geoms from `model_draft.ego_supply_res_powerplant`. Due to the bug mentioned above there're no geoms available. @Ludee is aware of it.

**Comment by Ludee** [comment]
We found a minor loop in the execution order.
The allocation of res to the MVGD is made in the REA-part (ego_dp_rea_setup.sql).
But this is executed after the PF scripts.

I will search for the relevant code and move to preprocessing res.

**Comment by Ludee** [comment]
I had a closer look and there were some allocations of the offshore wind in the rea_setup.
This was coded a long time ago before the preprocessing of the res existed.
I removed that part and should be OK by now. Please have another look @IlkaCu
